export const teamNameToHebrew = {
    ecuador: 'אקוודור',
    netherlands: 'הולנד',
    qatar: 'קטאר',
    senegal: 'סנגל',
    england: 'אנגליה',
    iran: 'איראן',
    'united states': 'ארצות הברית',
    wales: 'וויילס',
    argentina: 'ארגנטינה',
    mexico: 'מקסיקו',
    poland: 'פולין',
    'saudi arabia': 'ערב הסעודית',
    australia: 'אוסטרליה',
    denmark: 'דנמרק',
    france: 'צרפת',
    tunisia: 'תוניסיה',
    'costa rica': 'קוסטה ריקה',
    germany: 'גרמניה',
    japan: 'יפן',
    spain: 'ספרד',
    belgium: 'בלגיה',
    canada: 'קנדה',
    croatia: 'קרואטיה',
    morocco: 'מרוקו',
    brazil: 'ברזיל',
    cameroon: 'קמרון',
    serbia: 'סרביה',
    switzerland: 'שוויץ',
    ghana: 'גאנה',
    portugal: 'פורטוגל',
    'south korea': 'דרום קוריאה',
    uruguay: 'אורוגוואי',

    russia: 'רוסיה',
    egypt: 'מצרים',
    nigeria: 'ניגריה',
    iceland: 'איסלנד',
    sweden: 'שוודיה',
    panama: 'פנמה',
    colombia: 'קולומביה',
    turkey: 'טורקיה',
    italy: 'איטליה',
    finland: 'פינלנד',
    austria: 'אוסטריה',
    ukraine: 'אוקראינה',
    'north macedonia': 'צפון מקדוניה',
    'czech republic': 'צ\'כיה',
    scotland: 'סקוטלנד',
    slovakia: 'סלובקיה',
    hungary: 'הונגריה',
    peru: 'פרו',
    albania: 'אלבניה',
    georgia: 'גיאורגיה',
    romania: 'רומניה',
    slovenia: 'סלובניה',
}

export function getHebTeamName(name: string){
    return teamNameToHebrew[name.toLowerCase()] ?? name
}